export const CHATGPT_SECRET_CODES_SLUG = "100-chatgpt-secret-codes";

export type ChatGptCode = {
  num: string;
  name: string;
  does: string;
  example: string;
  bestFor: string;
};

export type ChatGptCodeSection = {
  id: string;
  title: string;
  blurb: string;
  codes: ChatGptCode[];
};

export const SECTIONS: ChatGptCodeSection[] = [
  {
    id: "01",
    title: "Get the truth",
    blurb: "When you need ChatGPT to stop being polite and start being useful.",
    codes: [
      {
        num: "01",
        name: "Truth mode",
        does: "ChatGPT stops trying to please you and tells you what it actually thinks, even when it stings.",
        example: "Truth mode. Here's my business plan \u2014 is it any good or am I kidding myself?",
        bestFor: "Gut-checking ideas you're attached to",
      },
      {
        num: "02",
        name: "/honest",
        does: "Drops the diplomatic hedging and gives you the blunt version with nothing to lose.",
        example: "/honest. Is this LinkedIn post landing or quietly embarrassing?",
        bestFor: "Feedback you suspect people are softening",
      },
      {
        num: "03",
        name: "Confidence check",
        does: "Before you trust an answer, ChatGPT rates its own confidence and flags exactly where it guessed.",
        example: "Answer this, then confidence check: how sure are you and where did you guess?",
        bestFor: "Research and facts you plan to act on",
      },
      {
        num: "04",
        name: "Red team",
        does: "ChatGPT attacks your plan from every angle a sharp critic would, so you find the holes first.",
        example: "Red team this launch plan. Tear it apart.",
        bestFor: "Pitches, plans, and big decisions",
      },
      {
        num: "05",
        name: "Steelman",
        does: "Builds the strongest version of the argument against you \u2014 the fastest way to find soft logic.",
        example: "Steelman the other side of: I should quit my job this quarter.",
        bestFor: "Testing a belief you hold strongly",
      },
      {
        num: "06",
        name: "Pre-mortem",
        does: "Pretends your plan already failed, then works backwards to tell you why while you can still fix it.",
        example: "Pre-mortem this. Assume it flopped in six months and tell me why.",
        bestFor: "Launches, partnerships, anything risky",
      },
      {
        num: "07",
        name: "No fluff",
        does: "Strips praise, throat-clearing, and filler. Just the useful parts.",
        example: "No fluff. What's wrong with this sales page?",
        bestFor: "When answers keep padding",
      },
      {
        num: "08",
        name: "Devil's advocate",
        does: "Argues the opposite of your position hard, then scores which side is stronger.",
        example: "Devil's advocate my pricing. Argue both sides, then pick a winner.",
        bestFor: "Sticky debates with yourself",
      },
      {
        num: "09",
        name: "Reality check",
        does: "Separates what you want to be true from what the evidence supports.",
        example: "Reality check. Am I ready to freelance full-time or still romanticizing it?",
        bestFor: "Career and money decisions",
      },
      {
        num: "10",
        name: "Risk rank",
        does: "Lists the real risks in order of likelihood \u00d7 impact, not vibes.",
        example: "Risk rank this product launch. Top five only.",
        bestFor: "Prioritizing what can actually kill the plan",
      },
    ],
  },
  {
    id: "02",
    title: "Think sharper",
    blurb: "Codes that upgrade how ChatGPT reasons through a problem with you.",
    codes: [
      {
        num: "11",
        name: "First principles",
        does: "Throws out recycled advice and rebuilds from what is actually true.",
        example: "First principles. How do I actually grow an audience from zero?",
        bestFor: "When every answer online sounds the same",
      },
      {
        num: "12",
        name: "Think harder",
        does: "Spends more effort before answering \u2014 for tradeoffs with no obvious answer.",
        example: "Should I take the offer or stay? Think harder.",
        bestFor: "Complex decisions",
      },
      {
        num: "13",
        name: "Step back",
        does: "Before answering, tells you the better question you should be asking instead.",
        example: "Step back first. What should I really be asking before I pick a niche?",
        bestFor: "When you're stuck on the wrong problem",
      },
      {
        num: "14",
        name: "Assumptions",
        does: "Lists every hidden assumption baked into your question before it responds.",
        example: "List the assumptions in my plan before you answer.",
        bestFor: "Spotting shaky ground under a decision",
      },
      {
        num: "15",
        name: "OODA",
        does: "Runs your decision through Observe, Orient, Decide, Act and gives the move.",
        example: "Run my pricing decision through OODA.",
        bestFor: "Fast decisions under pressure",
      },
      {
        num: "16",
        name: "Decision matrix",
        does: "Scores options against weighted criteria so the choice stops being a vibe.",
        example: "Put these three tools in a weighted decision matrix for my workflow.",
        bestFor: "Choosing between similar options",
      },
      {
        num: "17",
        name: "MECE",
        does: "Breaks the problem into buckets that don't overlap and don't leave gaps.",
        example: "MECE. Map every way this launch can fail.",
        bestFor: "Scoping messy problems",
      },
      {
        num: "18",
        name: "Second-order",
        does: "Shows what happens after the obvious first effect \u2014 the downstream consequences.",
        example: "Second-order effects of posting daily on LinkedIn for 90 days.",
        bestFor: "Strategy and habit decisions",
      },
      {
        num: "19",
        name: "Constraint flip",
        does: "Solves the problem under a brutal constraint so the real levers show up.",
        example: "Constraint flip: solve this with $0 and 3 hours a week.",
        bestFor: "When resources feel like the blocker",
      },
      {
        num: "20",
        name: "Tradeoff table",
        does: "Forces an explicit tradeoff between speed, quality, cost, and risk.",
        example: "Tradeoff table for shipping the MVP this month vs next quarter.",
        bestFor: "Product and project choices",
      },
    ],
  },
  {
    id: "03",
    title: "See what you're missing",
    blurb: "Codes for the blind spots you can't catch on your own.",
    codes: [
      {
        num: "21",
        name: "/blind",
        does: "Points out the blind spots you can't see because you're too close.",
        example: "/blind. What am I missing about this content strategy?",
        bestFor: "Work you've stared at too long",
      },
      {
        num: "22",
        name: "/mirror",
        does: "Reflects back who it thinks you are from everything you've said in the chat.",
        example: "/mirror. From this whole conversation, who do you think I am?",
        bestFor: "A sharp outside read on yourself",
      },
      {
        num: "23",
        name: "Unlearn",
        does: "Names things you probably believe about a topic that are actually wrong.",
        example: "Unlearn. What do most people get wrong about ChatGPT?",
        bestFor: "Clearing bad assumptions before you learn",
      },
      {
        num: "24",
        name: "Counterfactual",
        does: "Walks through exactly what changes if one key thing were different.",
        example: "Counterfactual: what changes if I had no ad budget?",
        bestFor: "Stress-testing a plan against reality",
      },
      {
        num: "25",
        name: "Insights",
        does: "Pulls non-obvious patterns out of your data or situation you'd skim past.",
        example: "Insights. Here are my last 30 days of posts \u2014 find the patterns.",
        bestFor: "Numbers, habits, hidden trends",
      },
      {
        num: "26",
        name: "Future self",
        does: "Answers as you, ten years from now, looking back at this moment.",
        example: "Answer as my future self in 10 years. Should I start the business now?",
        bestFor: "Decisions clouded by short-term fear",
      },
      {
        num: "27",
        name: "Audience gap",
        does: "Shows the gap between what you think you're saying and what the audience hears.",
        example: "Audience gap. Here's my pitch \u2014 what does a busy stranger actually hear?",
        bestFor: "Messaging and positioning",
      },
      {
        num: "28",
        name: "Incentive map",
        does: "Maps who benefits, who loses, and who will quietly resist.",
        example: "Incentive map for rolling out this AI workflow at work.",
        bestFor: "Change management",
      },
      {
        num: "29",
        name: "Failure modes",
        does: "Lists the top ways this fails in the real world, not in theory.",
        example: "Failure modes for my new newsletter. Be concrete.",
        bestFor: "New products and habits",
      },
      {
        num: "30",
        name: "Missing data",
        does: "Tells you what information you don't have yet that would change the answer.",
        example: "Missing data. What do I still need before deciding on this hire?",
        bestFor: "Decisions with incomplete info",
      },
    ],
  },
  {
    id: "04",
    title: "Learn and level up",
    blurb: "Codes that turn ChatGPT into the teacher you wish you had.",
    codes: [
      {
        num: "31",
        name: "ELI5",
        does: "Explains anything like you're five \u2014 perfect for dense jargon.",
        example: "ELI5 how RAG works in plain English.",
        bestFor: "Tax, contracts, AI jargon",
      },
      {
        num: "32",
        name: "Socrates",
        does: "Teaches by asking you questions until it clicks, instead of dumping answers.",
        example: "Socrates. Teach me prompt engineering by asking me questions.",
        bestFor: "Actually remembering what you learn",
      },
      {
        num: "33",
        name: "Expert mode",
        does: "Answers at top-expert level and assumes you can keep up \u2014 no dumbing down.",
        example: "Expert mode. Assume I know the basics. How does SEO really work now?",
        bestFor: "When ELI5 is too slow",
      },
      {
        num: "34",
        name: "Lindy",
        does: "Gives the time-tested approach that has worked for decades, not this week's trend.",
        example: "Lindy mode. What's the proven way to get fit \u2014 ignore the hype?",
        bestFor: "Cutting through fads",
      },
      {
        num: "35",
        name: "80-20",
        does: "Shows the small slice of effort that drives most of the result.",
        example: "80-20. What few ChatGPT habits actually move the needle?",
        bestFor: "When you're overwhelmed by options",
      },
      {
        num: "36",
        name: "Rubric",
        does: "Builds a scoring rubric, then grades your work against it honestly.",
        example: "Create a rubric for a strong cover letter, then score mine.",
        bestFor: "Improving anything you can measure",
      },
      {
        num: "37",
        name: "Curriculum",
        does: "Builds a learning path with milestones, practice drills, and checkpoints.",
        example: "Curriculum. Teach me SQL in 14 days with daily drills.",
        bestFor: "Skill acquisition",
      },
      {
        num: "38",
        name: "Quiz me",
        does: "Tests you, grades you, and rewrites the weak spots until you pass.",
        example: "Quiz me on this chapter until I score 90%.",
        bestFor: "Retention and exam prep",
      },
      {
        num: "39",
        name: "Analogy bank",
        does: "Gives three analogies at different levels until one sticks.",
        example: "Analogy bank. Explain APIs three ways \u2014 kid, coworker, engineer.",
        bestFor: "Hard concepts",
      },
      {
        num: "40",
        name: "Mistake log",
        does: "Anticipates the mistakes beginners make and how to catch them early.",
        example: "Mistake log for first-time freelancers. What will I mess up?",
        bestFor: "Starting something new",
      },
    ],
  },
  {
    id: "05",
    title: "Write and ship",
    blurb: "Codes for turning ChatGPT into your writer, editor, and finisher.",
    codes: [
      {
        num: "41",
        name: "D3",
        does: "Gives three completely different versions so you pick the best.",
        example: "D3. Write a message asking my boss for a raise.",
        bestFor: "Messages, captions, tone-sensitive copy",
      },
      {
        num: "42",
        name: "/human",
        does: "Rewrites stiff, robotic text so it reads like a person wrote it.",
        example: "/human. Rewrite this email so it sounds like me, not a template.",
        bestFor: "Making AI drafts sound natural",
      },
      {
        num: "43",
        name: "Compress",
        does: "Cuts the fluff and gives the essential version \u2014 down to a line if you want.",
        example: "Compress this into one tweet without losing the point.",
        bestFor: "Tightening long, rambly text",
      },
      {
        num: "44",
        name: "Persona",
        does: "Rewrites for a specific reader so it actually lands.",
        example: "Rewrite this pitch for a busy CEO who skims.",
        bestFor: "Matching message to audience",
      },
      {
        num: "45",
        name: "Template",
        does: "Turns a one-off into a reusable template you can fill forever.",
        example: "Turn this proposal into a blank template I can reuse.",
        bestFor: "Anything you do more than once",
      },
      {
        num: "46",
        name: "Voice lock",
        does: "Matches your voice from samples, then stays locked for the draft.",
        example: "Voice lock from these 3 posts. Rewrite this announcement in my voice.",
        bestFor: "Brand-consistent content",
      },
      {
        num: "47",
        name: "Hook ladder",
        does: "Generates ranked opening lines from safe to bold.",
        example: "Hook ladder for a reel about ChatGPT Work. Rank 10 hooks.",
        bestFor: "Social and email openers",
      },
      {
        num: "48",
        name: "Edit pass",
        does: "Does a structural edit first, then a line edit \u2014 separately.",
        example: "Edit pass. Structure first, then lines. Here's the draft.",
        bestFor: "Long-form writing",
      },
      {
        num: "49",
        name: "CTA forge",
        does: "Builds clear calls to action with options for soft, direct, and urgent.",
        example: "CTA forge for my webinar signup. Soft, direct, urgent.",
        bestFor: "Landing pages and posts",
      },
      {
        num: "50",
        name: "Ship checklist",
        does: "Runs a pre-publish checklist: clarity, claims, tone, and missing pieces.",
        example: "Ship checklist this LinkedIn carousel before I post.",
        bestFor: "Final QA before publish",
      },
    ],
  },
  {
    id: "06",
    title: "Work and ops",
    blurb: "Codes for email, meetings, plans, and the day-to-day grind.",
    codes: [
      {
        num: "51",
        name: "Inbox triage",
        does: "Sorts messages into reply today, this week, and ignore \u2014 with draft replies.",
        example: "Inbox triage. Here's my email dump from the last 7 days.",
        bestFor: "Email overload",
      },
      {
        num: "52",
        name: "Meeting digest",
        does: "Turns messy notes into decisions, owners, and next steps.",
        example: "Meeting digest. Extract decisions, owners, and deadlines.",
        bestFor: "After every meeting",
      },
      {
        num: "53",
        name: "Agenda builder",
        does: "Builds a tight agenda with timeboxes and desired outcomes.",
        example: "Agenda builder for a 30-min hiring sync. Outcomes first.",
        bestFor: "Running better meetings",
      },
      {
        num: "54",
        name: "Status update",
        does: "Writes a crisp status update: done, blocked, next \u2014 no fluff.",
        example: "Status update for my manager from these notes.",
        bestFor: "Weekly reporting",
      },
      {
        num: "55",
        name: "SOP draft",
        does: "Turns a messy process into a step-by-step SOP someone else can run.",
        example: "SOP draft for how I publish a newsletter every Friday.",
        bestFor: "Delegating and systems",
      },
      {
        num: "56",
        name: "Prioritize",
        does: "Ranks your list by impact vs effort and tells you what to cut.",
        example: "Prioritize this task list. Kill anything that doesn't move the goal.",
        bestFor: "Overloaded weeks",
      },
      {
        num: "57",
        name: "Negotiation script",
        does: "Builds talking points, counters, and walk-away lines.",
        example: "Negotiation script for raising my freelance rate 30%.",
        bestFor: "Salary and client talks",
      },
      {
        num: "58",
        name: "Follow-up ladder",
        does: "Writes a sequence of follow-ups that escalate without being annoying.",
        example: "Follow-up ladder for a client who ghosted after the proposal.",
        bestFor: "Sales and partnerships",
      },
      {
        num: "59",
        name: "Job pack",
        does: "Builds resume bullets, cover letter, and interview answers from one story bank.",
        example: "Job pack for this role using my experience below.",
        bestFor: "Job applications",
      },
      {
        num: "60",
        name: "Week plan",
        does: "Turns goals into a realistic weekly plan with buffers and focus blocks.",
        example: "Week plan. Goals: ship the deck, close 2 leads, rest Sunday.",
        bestFor: "Weekly planning",
      },
    ],
  },
  {
    id: "07",
    title: "Research and data",
    blurb: "Codes for digging, comparing, and making numbers useful.",
    codes: [
      {
        num: "61",
        name: "Research brief",
        does: "Scopes the question, sources needed, and what done looks like before diving in.",
        example: "Research brief. Competitors in AI coaching for freelancers.",
        bestFor: "Starting any research job",
      },
      {
        num: "62",
        name: "Source grade",
        does: "Rates each claim by evidence quality and flags weak links.",
        example: "Source grade this article. What's solid vs speculative?",
        bestFor: "Due diligence",
      },
      {
        num: "63",
        name: "Compare grid",
        does: "Builds a side-by-side comparison with criteria you care about.",
        example: "Compare grid: Notion vs Obsidian vs Capacities for a second brain.",
        bestFor: "Tool and vendor choices",
      },
      {
        num: "64",
        name: "Summarize deep",
        does: "Multi-pass summary: one line, one paragraph, then key takeaways and open questions.",
        example: "Summarize deep this transcript.",
        bestFor: "Long docs and calls",
      },
      {
        num: "65",
        name: "Extract",
        does: "Pulls structured fields from messy text into a clean table.",
        example: "Extract: company, role, salary, location from these job posts.",
        bestFor: "Cleaning unstructured data",
      },
      {
        num: "66",
        name: "Trend scan",
        does: "Separates lasting trends from noise and hype cycles.",
        example: "Trend scan. What's real vs hype in AI agents right now?",
        bestFor: "Market reading",
      },
      {
        num: "67",
        name: "Number story",
        does: "Turns a spreadsheet dump into a narrative a human can act on.",
        example: "Number story. What moved, why, and the one action.",
        bestFor: "Weekly metrics",
      },
      {
        num: "68",
        name: "Cite or cut",
        does: "Only keeps claims it can support; cuts or marks the rest as unknown.",
        example: "Cite or cut. Rewrite this section with only supported claims.",
        bestFor: "Trustworthy writing",
      },
      {
        num: "69",
        name: "Interview guide",
        does: "Builds questions that get useful answers, not fluff.",
        example: "Interview guide for customer discovery with early adopters.",
        bestFor: "User research",
      },
      {
        num: "70",
        name: "Brief to brief",
        does: "Turns raw research into an exec brief under one page.",
        example: "Brief to brief. One page for leadership from these notes.",
        bestFor: "Leadership updates",
      },
    ],
  },
  {
    id: "08",
    title: "Build with ChatGPT",
    blurb: "Codes that lean on Canvas, code, files, and interactive output.",
    codes: [
      {
        num: "71",
        name: "Canvas mode",
        does: "Asks for a Canvas doc or app you can edit live instead of a chat dump.",
        example: "Canvas mode. Build a one-page project brief I can edit with you.",
        bestFor: "Collaborative drafting",
      },
      {
        num: "72",
        name: "Spreadsheet",
        does: "Builds formulas, structure, and sample data you can download and use.",
        example: "Spreadsheet. Build a content calendar with status and due dates.",
        bestFor: "Ops trackers",
      },
      {
        num: "73",
        name: "Code it",
        does: "Writes working code, explains it, and includes how to run it.",
        example: "Code it. A Python script that renames files by date.",
        bestFor: "Automations and tools",
      },
      {
        num: "74",
        name: "Debug",
        does: "Diagnoses errors from the message and the surrounding code, then patches.",
        example: "Debug. Here's the error and the function. Fix it and explain why.",
        bestFor: "Broken scripts",
      },
      {
        num: "75",
        name: "Prototype",
        does: "Ships a minimal interactive prototype you can click through.",
        example: "Prototype a simple habit tracker UI I can try in Canvas.",
        bestFor: "Product ideas",
      },
      {
        num: "76",
        name: "Diagram",
        does: "Draws the system as a clear diagram or flowchart in text/mermaid.",
        example: "Diagram the customer onboarding flow end to end.",
        bestFor: "Process clarity",
      },
      {
        num: "77",
        name: "Prompt pack",
        does: "Turns one workflow into a reusable pack of prompts with inputs/outputs.",
        example: "Prompt pack for my weekly content pipeline.",
        bestFor: "Repeatable AI workflows",
      },
      {
        num: "78",
        name: "Custom GPT brief",
        does: "Writes instructions, knowledge needs, and test cases for a Custom GPT.",
        example: "Custom GPT brief for a brand-voice editor that never invents claims.",
        bestFor: "Building Custom GPTs",
      },
      {
        num: "79",
        name: "File audit",
        does: "Reviews an uploaded file for structure, gaps, and quick wins.",
        example: "File audit this spreadsheet. What's messy and what to fix first?",
        bestFor: "Spreadsheets and docs",
      },
      {
        num: "80",
        name: "Automate recipe",
        does: "Designs a no-code or light-code automation with triggers and steps.",
        example: "Automate recipe: new Typeform lead \u2192 Slack + Notion + thank-you email.",
        bestFor: "Ops automation",
      },
    ],
  },
  {
    id: "09",
    title: "Content and brand",
    blurb: "Codes for creators, marketers, and anyone shipping content weekly.",
    codes: [
      {
        num: "81",
        name: "Content engine",
        does: "Turns one idea into a week's worth of posts across formats.",
        example: "Content engine. One idea: 'AI won't replace you, workflows will.'",
        bestFor: "Weekly content planning",
      },
      {
        num: "82",
        name: "Hook + body + CTA",
        does: "Forces every draft into hook, body, CTA \u2014 no wandering.",
        example: "Hook + body + CTA for a carousel on ChatGPT Projects.",
        bestFor: "Social posts that convert",
      },
      {
        num: "83",
        name: "Story spine",
        does: "Structures a story with setup, tension, turn, and takeaway.",
        example: "Story spine for a founder story about almost quitting.",
        bestFor: "Reels and keynotes",
      },
      {
        num: "84",
        name: "Brand voice card",
        does: "Builds a one-pager of voice rules, do/don't, and sample lines.",
        example: "Brand voice card from these 5 posts I love.",
        bestFor: "Consistent brand writing",
      },
      {
        num: "85",
        name: "Objection crush",
        does: "Lists the top objections and writes replies that don't sound defensive.",
        example: "Objection crush for 'I don't have time to learn AI.'",
        bestFor: "Sales and comments",
      },
      {
        num: "86",
        name: "SEO outline",
        does: "Builds a search-aware outline with intent, FAQs, and internal link ideas.",
        example: "SEO outline for 'how to use ChatGPT for business'.",
        bestFor: "Blog and landing pages",
      },
      {
        num: "87",
        name: "Thumbnail text",
        does: "Writes short, punchy on-image text options for thumbnails.",
        example: "Thumbnail text. 12 options under 6 words for this YouTube title.",
        bestFor: "YouTube and ads",
      },
      {
        num: "88",
        name: "Repurpose",
        does: "Takes one long piece and slices it into platform-native formats.",
        example: "Repurpose this newsletter into LinkedIn, X, and a short script.",
        bestFor: "One-to-many content",
      },
      {
        num: "89",
        name: "Series map",
        does: "Plans a multi-part series with cliffhangers and payoffs.",
        example: "Series map. 5-part series teaching ChatGPT Work from zero.",
        bestFor: "Course and series content",
      },
      {
        num: "90",
        name: "Comment bait",
        does: "Writes endings that invite a specific, easy comment.",
        example: "Comment bait. End this post so people reply with their stack.",
        bestFor: "Engagement on social",
      },
    ],
  },
  {
    id: "10",
    title: "Agent and power moves",
    blurb: "Codes for Projects, Work, memory, and long autonomous runs.",
    codes: [
      {
        num: "91",
        name: "Project brain",
        does: "Sets up Project instructions: goals, constraints, voice, and what never to invent.",
        example: "Project brain. Write instructions for my 'Client Delivery' Project.",
        bestFor: "ChatGPT Projects",
      },
      {
        num: "92",
        name: "Work brief",
        does: "Writes a ChatGPT Work brief with outcome, apps, approvals, and definition of done.",
        example: "Work brief. Weekly metrics report from Sheet + Slack digest. No sending.",
        bestFor: "ChatGPT Work agents",
      },
      {
        num: "93",
        name: "Plan mode",
        does: "Forces a plan first \u2014 steps, risks, and checkpoints \u2014 before any build.",
        example: "Plan mode. Show the plan for this campaign pack before you build.",
        bestFor: "Long agent tasks",
      },
      {
        num: "94",
        name: "Memory write",
        does: "Saves durable preferences as clear memory notes, not vague vibes.",
        example: "Memory write. Remember: short answers, no emojis, British spelling.",
        bestFor: "Persistent preferences",
      },
      {
        num: "95",
        name: "Continue",
        does: "Restarts a stalled agent from the last verified step, not from scratch.",
        example: "Continue from the last verified step. Don't re-derive what's done.",
        bestFor: "Long runs that pause",
      },
      {
        num: "96",
        name: "Verify",
        does: "Audits claims against files/tool results before reporting progress.",
        example: "Verify. Only report what you can point to in the files.",
        bestFor: "Stopping confident nonsense",
      },
      {
        num: "97",
        name: "Guardrails",
        does: "Sets hard rules: what it can touch, what needs approval, what is off-limits.",
        example: "Guardrails. Draft only. Never send email or post. Ask before deletes.",
        bestFor: "Safe agent setup",
      },
      {
        num: "98",
        name: "Sol lane",
        does: "Routes the hard, multi-step job to deeper reasoning (Sol / high effort).",
        example: "Sol lane. Architecture decision across 4 services \u2014 don't rush.",
        bestFor: "Hard reasoning jobs",
      },
      {
        num: "99",
        name: "Terra lane",
        does: "Routes scoped everyday work to the balanced default (Terra).",
        example: "Terra lane. Draft the weekly update and a clean checklist.",
        bestFor: "Everyday agentic work",
      },
      {
        num: "100",
        name: "Luna lane",
        does: "Routes bulk/low-stakes volume work to the fast cheap lane (Luna).",
        example: "Luna lane. Tag and summarize these 40 support tickets.",
        bestFor: "Bulk cleanup and tagging",
      },
    ],
  },
];
