export type ScenePrompt = { num: string; title: string; text: string };

export type SceneGroup = { group: string; scenes: ScenePrompt[] };

export const SCENE_GROUPS: SceneGroup[] = [
  {
    group: "Home & loungewear",
    scenes: [
      {
        num: "01",
        title: "Lazy morning in bed",
        text: "Create a photorealistic vertical lifestyle portrait of the woman in the reference image lying back in a cozy bed on a slow morning, blending naturally as if she genuinely just woke up and grabbed her phone. The setting is a soft, sunlit bedroom with crisp white bedding, layered white pillows, a plush blush-pink throw blanket, sheer white curtains diffusing gentle morning light, and warm wooden furniture softly out of focus behind her. Dress her in an oversized white cotton t-shirt with a small pastel graphic print, worn loose and relaxed, with a satin blush-pink sleep mask pushed up onto her forehead and her hair down in soft natural waves across the pillow. Her makeup should be bare or barely there and suited to her own face, fresh just-woke-up skin with natural texture, a slight morning flush, soft brows, and natural lips, rendered realistically with no plastic smoothing. Pose her reclined against the pillows at a relaxed diagonal, holding a modern smartphone up in both hands as she looks at the screen with a playful scrunched expression, shoulders sunk into the bedding. Frame it as an intimate vertical shot from slightly above using a 35mm lens at f/2.2 with natural depth of field. Keep soft natural window light from the side, gentle realistic shadows in the bedding, fine grain, true fabric texture, and an authentic lazy-morning mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or fingers on the phone.",
      },
      {
        num: "02",
        title: "Cozy chic on the sofa",
        text: "Create a photorealistic vertical lifestyle portrait of the woman in the reference image seated on a sofa in a bright minimal living room, blending naturally as if it is a relaxed at-home moment. The setting is a clean airy room with an oatmeal fabric sofa, a tall green palm plant, framed art, a large window with soft daylight, and pale wood floors. Dress her in a fitted black ribbed short-sleeve top and matching black ribbed leggings as a sleek loungewear set, barefoot, with her hair in its natural voluminous curls. Her makeup should be soft and suited to her own face, glowing skin with natural texture, soft brows, clean lashes, and a natural lip. Pose her seated near the edge of the sofa with one knee bent up and one foot on the cushion, one hand resting beside her, torso turned slightly toward the camera, relaxed and confident. Frame it as a vertical three-quarter to full-body shot from chest height using a 35mm lens at f/2.2 with natural depth. Use soft natural window light with gentle realistic shadows, fine grain, true ribbed-fabric texture, and an authentic cozy at-home mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or feet.",
      },
      {
        num: "03",
        title: "Warm luxe loungewear",
        text: "Create a photorealistic vertical lifestyle portrait of the woman in the reference image lounging on a cream sofa in a warm luxurious living room, blending naturally as if it is a real cozy evening at home. The setting is an upscale room with a soft ivory couch, plush cushions, and tall backlit wooden built-in shelves displaying vases, books, and sculptural decor with a gentle amber glow. Dress her in a cozy cinnamon-brown fuzzy knit lounge set, a soft cardigan over a matching top and wide-leg knit pants, styled with sleek straight hair and a soft side part and neutral manicured nails. Her makeup should be soft glam suited to her own face, glowing skin with natural texture, defined brows, soft warm eyes, clean lashes, and a nude lip. Pose her reclined sideways into the corner of the sofa with one arm draped along the cushions and the other resting on her leg, calm and content. Frame it as a vertical three-quarter portrait from chest height using a 50mm lens at f/2.2 with shallow depth. Use cozy warm interior lighting with soft realistic shadows, fine grain, true fuzzy-knit texture, believable warmth on the wood, and an authentic luxe-loungewear mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or fingers.",
      },
    ],
  },
  {
    group: "Self-care & kitchen",
    scenes: [
      {
        num: "04",
        title: "Spa-morning kitchen selfie",
        text: "Create a photorealistic vertical selfie-style portrait of the woman in the reference image taking an arm's-length selfie in a bright modern kitchen during her morning self-care routine, blending naturally as if she genuinely snapped it herself. The setting is a clean contemporary kitchen with a marble waterfall island, pale wood cabinetry, a woven rattan pendant light, and soft daylight filling the room. Dress her in a fitted white short-sleeve top and matching white leggings, a puffy blush-pink spa headband holding her hair back, and style her with long soft waves; she wears glittery silver hydrating under-eye patches and holds a tall glass of iced matcha in one hand while the other arm extends toward the camera. Her makeup should be minimal and suited to her own face, dewy clean skin with natural texture, soft brows, fluttered lashes, and a natural lip. Pose her front-on with the selfie arm extended, a slight lean toward the lens, relaxed confident expression. Frame it as a vertical front-camera selfie from arm's length at chest height with the mild wide-angle look of a phone selfie. Use soft even daylight, gentle realistic shadows, fine grain, true skin and fabric texture, and an authentic clean-girl morning mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or fingers.",
      },
      {
        num: "05",
        title: "Smoothie in a bright kitchen",
        text: "Create a photorealistic vertical lifestyle portrait of the woman in the reference image making a fruit smoothie in a bright airy kitchen, blending naturally as if she is genuinely mid-routine. The setting is a sunlit white kitchen with pale blue-grey cabinetry, a white marble island, large windows flooding the room with soft daylight, and a countertop blender filled with colorful fruit; on the island sits a white plate of fresh spinach, sliced strawberries and banana, and a paper bag of sugar. Dress her in a fitted red athletic bandeau top and matching red sweatpants with a drawstring, showing a toned midriff, casual and sporty; style her with long loose waves. Her makeup should be soft and suited to her own face, glowing skin with natural texture, soft brows, clean lashes, and a natural lip. Pose her standing at the island, looking down as she drops a strawberry into the blender with one hand, the other resting near the jug. Frame it as a vertical three-quarter to full-body shot from slightly across the island at chest height using a 35mm lens at f/2.5 with natural depth. Use airy natural daylight from the windows, soft realistic shadows, fine grain, true fabric and food texture, believable reflections on the marble and blender, and an authentic healthy-morning mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or props.",
      },
      {
        num: "06",
        title: "Pajamas, pouring juice on the counter",
        text: "Create a photorealistic vertical lifestyle portrait of the woman in the reference image perched on a kitchen counter pouring orange juice into a glass on a soft morning, blending naturally as if it is a real candid moment. The setting is a charming kitchen with sage-green shaker cabinetry, a textured stone backsplash, hanging utensils and sieves on a rail, a knife block, and a classic black range stove, lit by gentle daylight. Dress her in a dainty floral pajama set, a fitted cami top and relaxed wide-leg lounge pants in a cream cherry-and-rose print, with small pink bow clips in her hair worn down in soft waves, and delicate gold necklaces. Her makeup should be soft and suited to her own face, fresh glowing skin with natural texture, soft brows, clean lashes, and a natural lip. Pose her seated sideways on the countertop with legs together and slightly bent, looking down as she pours juice from a glass bottle into a held glass, shoulders relaxed. Frame it as a vertical full-body shot from across the kitchen at roughly counter height using a 35mm lens at f/2.2 with natural depth. Use soft natural morning light, gentle realistic shadows, fine grain, true fabric texture, believable liquid and glass highlights as the juice pours, and an authentic cozy-morning mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or props.",
      },
    ],
  },
  {
    group: "Fitness",
    scenes: [
      {
        num: "07",
        title: "Gym mirror selfie",
        text: "Create a photorealistic vertical mirror selfie of the woman in the reference image taking a phone mirror selfie in a minimal studio or gym corner, blending naturally as if she genuinely shot it in the mirror. The setting is a simple greige wall with soft natural shadow falling across it, clean and uncluttered. Dress her in a fitted matching athleisure set, a supportive scoop-neck sports bra and high-waist leggings in a muted plum-grey tone, showing a toned athletic figure; style her hair in its natural texture and volume. She holds a modern silver smartphone up beside her face for the mirror shot. Her makeup should be minimal and suited to her own face, fresh glowing skin with natural texture, soft brows, clean lashes, and natural lips. Pose her side-on to the mirror with hips angled, one hand at the waistband, the other raising the phone, chin slightly tilted, confident relaxed body language. Frame it as a vertical three-quarter mirror selfie at chest height with the slight phone-camera perspective and faint on-screen glow. Use soft directional light casting a gentle realistic shadow behind her, fine grain, true fabric and skin texture, and an authentic candid selfie feel, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or phone.",
      },
      {
        num: "08",
        title: "Padel court at golden hour",
        text: "Create a photorealistic vertical portrait of the woman in the reference image posing confidently on a rooftop padel court at golden hour, blending naturally into the scene as if she just finished a match. The setting is an elevated open-air court with bright green turf, a white net in the foreground, glass-and-mesh fencing, and a sweeping city skyline of glass towers across calm water behind her, all lit by warm low sunset light. Dress her in a fitted white short-sleeve tennis dress with a sporty cut, a pastel-green knit sweater tied loosely over her shoulders, a patterned sporty headband, and a small scrunchie on one wrist, holding a pink padel racket resting against one shoulder and a tennis ball in the other hand. Her makeup should be polished but sporty and suited to her own face, glowing sun-kissed skin with natural texture, soft bronzed warmth, defined brows, clean lashes, and natural lips. Pose her leaning back against the net with hips angled, one arm raised holding the racket by her shoulder, chin slightly lifted. Frame it as a vertical three-quarter portrait from roughly chest height using a 50mm lens at f/2.2 with shallow depth of field. Use warm directional sunset light from the side, golden highlights on her skin and hair, soft long shadows on the turf, fine grain, realistic fabric texture, and authentic outdoor lighting, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or racket.",
      },
    ],
  },
  {
    group: "Going out & fashion",
    scenes: [
      {
        num: "09",
        title: "Glam luxe, full-body indoor",
        text: "Create a photorealistic vertical full-body portrait of the woman in the reference image standing in a softly lit room styled for a glam outfit shot, blending naturally as if it is a real at-home fashion photo. The setting is a simple interior with a warm cream wall, a wooden baseboard, and pale beige carpet, clean and minimal so the outfit stands out. Dress her in a strapless red tweed corset top with gold buttons down the front, paired with baggy wide-leg distressed washed-black jeans that pool slightly over pointed-toe red heels; style her with sleek straight long hair in a center part, a chunky gold choker, large gold hoop earrings, gold cuff bracelets, and stacked gold rings, holding a small red patent quilted top-handle bag. Her makeup should be polished glam suited to her own face, glowing skin with natural texture, defined brows, softly blended eyeshadow, clean lashes, and a soft natural lip. Pose her front-on with weight slightly on one leg, both hands resting low at her hips and thighs, chin level, expression calm and confident. Frame it as a vertical full-body shot from chest height using a 50mm lens at f/2.5 with natural depth. Use soft even indoor lighting with gentle realistic shadows, fine grain, true fabric texture in the tweed and denim, believable sheen on the patent bag and gold jewelry, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or props.",
      },
      {
        num: "10",
        title: "High-fashion OOTD at home",
        text: "Create a photorealistic vertical full-body portrait of the woman in the reference image posing in a chic modern apartment, blending naturally as if it is a real OOTD photo. The setting is a refined living room with a crystal cascade chandelier, a neutral console with sculptural decor, a soft sofa, pale walls, and wood flooring, with gentle daylight. Dress her in a light-blue oversized shirt worn draped off the shoulders over a grey strapless corset top, grey tailored wide-leg trousers, a layered chain-and-pearl belt slung low on the hips, a slim chain crossbody strap across the body, oversized square dark sunglasses, and a silver watch; style her hair sleek and slicked back. Her makeup should be polished and suited to her own face, glowing skin with natural texture, defined brows, soft glam eyes, clean lashes, and a nude lip. Pose her standing front-on with both hands tucked into the trouser pockets, hips squared, chin level behind the sunglasses, cool and confident. Frame it as a vertical full-body shot from chest height using a 35mm lens at f/2.5 with natural depth. Use soft natural interior light with gentle realistic shadows, fine grain, true fabric texture, believable sheen on the chains and sunglasses, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or props.",
      },
      {
        num: "11",
        title: "Luxury boutique, leopard maxi",
        text: "Create a photorealistic vertical full-body portrait of the woman in the reference image posing elegantly outside a luxury boutique, blending naturally as if it is a real travel fashion photo. The setting is a polished beige stone wall with an embossed crest emblem and subtle engraved lettering behind her, smooth flooring underfoot, and soft daylight, an upscale and minimal backdrop. Dress her in a fitted navy sleeveless boat-neck ruched top and a long leopard-print bias-cut satin maxi skirt with a mermaid silhouette skimming the floor, styled with sleek pulled-back hair, dark sunglasses, delicate gold jewelry, and a slim gold bracelet, holding a small black half-moon shoulder bag. Her makeup should be polished and suited to her own face, glowing skin with natural texture, defined brows, soft glam eyes, clean lashes, and a neutral lip. Pose her standing tall and angled slightly to one side, one hand raised gracefully toward her face, the other holding the bag at her hip, poised and confident. Frame it as a vertical full-body shot from slightly low at hip height to lengthen the silhouette, using a 50mm lens at f/2.8 with natural depth. Use soft natural daylight with gentle realistic shadows, fine grain, true satin and fabric texture, believable sheen on the bag and sunglasses, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or props.",
      },
      {
        num: "12",
        title: "Sunny city street, satin cami and denim",
        text: "Create a photorealistic vertical full-body portrait of the woman in the reference image posing on a sunny city street outside an elegant townhouse, blending naturally as if it is a real summer street photo. The setting is a bright European-style street with a pale stone building, a black wrought-iron railing and stair handrail, a tall potted palm, and a planter of white flowers beside her, all in warm midday sunlight. Dress her in a wine-red satin cowl-neck cami top with delicate lace trim and thin straps, paired with a long denim maxi skirt, a burgundy crochet beanie, a silver watch and bracelets, and metallic sandals, holding a fluffy hot-pink feather handbag. Her makeup should be soft glam suited to her own face, glowing sun-kissed skin with natural texture, defined brows, soft warm eyes, clean lashes, and a glossy nude lip. Pose her leaning lightly against the railing with one knee bent, one hand raised to the side of her head, the other holding the feather bag, relaxed and breezy. Frame it as a vertical full-body shot from chest height using a 35mm lens at f/2.5 with natural depth. Use bright natural sunlight with warm highlights and soft realistic shadows, fine grain, true satin and denim texture, believable movement in the feather bag, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or props.",
      },
      {
        num: "13",
        title: "Evening leather-sofa editorial",
        text: "Create a photorealistic vertical editorial portrait of the woman in the reference image seated on a leather sofa in a moody, low-lit evening setting, blending naturally as if it is a genuine night-in editorial moment. The setting is a dim, warm-toned room with a deep-brown tufted leather sofa, a vintage patterned rug beneath, and soft shadowy walls fading into the background under low ambient lighting. Dress her in a sleek sleeveless black mock-neck top tucked into a brown suede midi skirt with a high side slit, paired with tall glossy burgundy crocodile-pattern knee-high heeled boots, styled minimal and chic with sleek straight long hair and a couple of slim rings. Her makeup should be polished evening glam suited to her own face, smooth glowing skin with natural texture, defined brows, soft smoky-neutral eyes, clean lashes, and a natural lip. Pose her seated with her body angled across the sofa, legs crossed to show the boots and the slit, one hand resting on her thigh, chin slightly lowered with a calm confident gaze toward the camera. Frame it as a vertical three-quarter to full-body shot from slightly low at seated height using a 50mm lens at f/2.0 with shallow depth. Use warm low directional lighting with rich realistic shadows and gentle highlights on the leather, suede, and boots, fine grain, true material textures, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, legs, or boots.",
      },
    ],
  },
  {
    group: "Cafe",
    scenes: [
      {
        num: "14",
        title: "Cafe window coffee",
        text: "Create a photorealistic vertical portrait of the woman in the reference image seated by a cafe window holding a coffee, blending naturally as if it is a candid cafe moment. The setting is a stylish corner cafe with a large window beside her reflecting street signage, parked cars, and greenery, soft daylight through the glass. Dress her in a fitted white off-shoulder ribbed long-sleeve top, brown rectangular sunglasses, delicate gold necklaces, several ear hoops, stacked rings, and warm-toned nails, hair in a sleek high bun. Her makeup should be soft glam suited to her own face, glowing skin with natural texture, defined brows, soft warm eyes, clean lashes, and a nude lip. Pose her seated holding a small black coffee cup with both hands near her chest, elbows resting, torso angled toward the window light, calm and chic. Frame it as a vertical chest-up to waist portrait from across the table at eye level using a 50mm lens at f/2.0 with shallow depth. Use soft natural window light with gentle realistic shadows, fine grain, true ribbed-knit texture, believable sheen on the cup and sunglasses, and an authentic cafe mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or fingers.",
      },
      {
        num: "15",
        title: "Outdoor cafe terrace matcha",
        text: "Create a photorealistic vertical portrait of the woman in the reference image seated at an outdoor cafe terrace with iced matcha, blending naturally as if it is a real chic city outing. The setting is a stylish open-air terrace with a green bistro table, a large parasol pole, potted greenery, a glass storefront behind, and pale-stone buildings with cathedral spires in the soft overcast distance. Dress her in a cream ribbed long-sleeve scoop-neck top, a padded white headband, a delicate gold necklace, with a soft fur shoulder bag resting on the chair, and very long dark wavy hair worn down. Her makeup should be soft glam suited to her own face, glowing skin with natural texture, defined brows, soft neutral eyes, clean lashes, and a glossy nude lip. Pose her seated with one elbow on the table and her hand resting against her cheek, two iced green drinks in front of her, body angled toward the camera, poised and relaxed. Frame it as a vertical chest-up to waist portrait from across the table at eye level using a 50mm lens at f/2.0 with shallow depth. Use soft natural daylight with gentle realistic shadows, fine grain, true knit texture, believable condensation on the iced cups, and an authentic posh-cafe mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or fingers.",
      },
    ],
  },
  {
    group: "Beach",
    scenes: [
      {
        num: "16",
        title: "Beach selfie, hibiscus and red top",
        text: "Create a photorealistic vertical selfie of the woman in the reference image on a sunny beach, blending naturally as if she genuinely took it herself. The setting is a bright sandy beach in full daylight with soft footprints in pale sand and warm sun overhead. Dress her in a red ruffled cami top with thin straps, a white hibiscus tucked behind one ear, stacked gold bangles, gold rings, a fine gold necklace, and playful floral-print long nails, hair slicked into a low bun. Her makeup should be sun-kissed and suited to her own face, dewy flushed skin with natural texture and a touch of sunscreen sheen, soft brows, clean lashes, and a glossy lip, with a bright happy expression. Pose her seated on the sand with one arm extended toward the camera for the selfie and the other hand raised playfully near her mouth, a candid winking smile. Frame it as a vertical front-camera selfie from arm's length at a slight high angle with the mild wide-angle look of a phone selfie. Use bright natural sunlight with warm highlights and soft realistic shadows on the sand, fine grain, true fabric and skin texture, believable petals on the flower, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or nails.",
      },
      {
        num: "17",
        title: "Glam beach by the surf",
        text: "Create a photorealistic vertical overhead selfie of the woman in the reference image lying on wet sand near the surf, blending naturally as if she shot it looking up at the camera. The setting is a beach at the waterline with damp packed sand, gentle white foam from a receding wave at the top of the frame, and a few scattered shells. Dress her in a white halter or one-shoulder swimsuit top, chunky gold cuff bangles, hair in a dark wavy pinned updo with a few loose strands. Her makeup should be glam and suited to her own face, glowing skin with natural texture, defined brows, soft smoky lined eyes, clean lashes, and a glossy nude lip. Pose her reclined on the sand with one hand raised softly to her cheek, head tilted up toward the lens, relaxed and elegant. Frame it as a vertical chest-up portrait from directly above at a slight angle, as if holding the phone overhead. Use bright natural daylight with soft realistic shadows, fine grain, true sand and skin texture, believable damp sheen on the sand with a little clinging to the skin, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or fingers.",
      },
      {
        num: "18",
        title: "Tropical close-up beach selfie",
        text: "Create a photorealistic vertical close-up selfie of the woman in the reference image lying on a tropical beach, blending naturally as if she genuinely took it herself. The setting is a bright sunny beach with pale sand, a vivid blue sky with soft white clouds, palm trees and turquoise ocean with a few people softly blurred far behind. Dress her in a patterned bikini with thin straps, a fine gold necklace, a pale jade bangle, long French-tip nails, hair slicked back wet with a few loose baby hairs, and black rectangular sunglasses pushed slightly down the nose. Her makeup should be minimal and suited to her own face, dewy sun-kissed skin with real texture and a hint of sweat sheen, soft full brows, clean lashes, and a glossy lip. Pose her lying on the sand resting her chin near her crossed hands, looking over the top of the sunglasses toward the lens, relaxed and sultry. Frame it as a vertical tight close-up from arm's length at a low angle with the mild wide-angle look of a phone selfie. Use bright natural sunlight with warm highlights and soft realistic shadows, fine grain, true skin and sand texture, believable shine on the sunglasses and skin, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or nails.",
      },
    ],
  },
  {
    group: "Travel",
    scenes: [
      {
        num: "19",
        title: "Airplane, cozy pink hoodie",
        text: "Create a photorealistic vertical lifestyle portrait of the woman in the reference image seated in a roomy airplane seat dressed for a cozy flight, blending naturally as if it is a real candid travel moment. The setting is a clean modern cabin with a window seat, teal-and-grey upholstery, a soft blanket draped beside her, a dim window, and a tray table with a phone and a snack pouch. Dress her in an oversized soft pink hooded sweatshirt with the hood up, white over-ear headphones, long dark hair with soft bangs framing her face, and cute long nails. Her makeup should be soft and suited to her own face, fresh glowing skin with natural texture, soft brows, clean lashes, and a natural lip. Pose her seated with both hands raised in playful peace signs toward the camera, a relaxed cute expression, a snack pouch on her lap. Frame it as a vertical chest-up to waist portrait from across the aisle at seated eye level using a 35mm lens at f/2.5 with natural depth. Use soft ambient cabin lighting with gentle realistic shadows, fine grain, true soft-fabric texture, believable highlights on the headphones, and an authentic cozy-travel mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or fingers.",
      },
      {
        num: "20",
        title: "Airport gate, knit travel set",
        text: "Create a photorealistic vertical lifestyle portrait of the woman in the reference image seated at an airport gate, blending naturally as if it is a real candid travel moment. The setting is a bright departure lounge with rows of dark blue seats, floor-to-ceiling windows showing planes parked on the tarmac under a soft sky. Dress her in a matching soft grey knit travel set, a zip cardigan and wide-leg knit pants, white over-ear headphones, a black headband, white low-top sneakers, with a tan leather tote beside her holding a small fuzzy bear charm and an iced drink on the floor nearby; style her with long dark hair worn down. Her makeup should be soft and suited to her own face, fresh glowing skin with natural texture, soft brows, clean lashes, and a natural lip. Pose her seated with legs crossed and hands resting in her lap, head turned slightly to gaze out toward the windows, relaxed and effortless. Frame it as a vertical full-body shot from across the seating at seated eye level using a 35mm lens at f/2.5 with natural depth. Use soft natural window light with gentle realistic shadows, fine grain, true knit texture, believable highlights on the headphones and tote, and an authentic airport-travel mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or feet.",
      },
      {
        num: "21",
        title: "Hotel mirror selfie, travel OOTD",
        text: "Create a photorealistic vertical mirror selfie of the woman in the reference image in a hotel room holding her phone, blending naturally as if she genuinely shot it in the mirror. The setting is a clean modern hotel room with a large mirror, a wood-toned desk with snacks and a welcome card behind her, a mini fridge, pale walls, and soft overhead lighting. Dress her in a fitted black tank crop top showing a toned midriff, a black shirt draped over the shoulders, black wide-leg sweatpants, and white low-top sneakers, with slim glasses, gold necklaces, hoop earrings, and a watch, hair in a sleek slicked-back low bun. Her makeup should be soft and suited to her own face, glowing skin with natural texture, soft brows, clean lashes, and a natural lip. Pose her standing side-on to the mirror, one hand raising the phone for the selfie and the other resting on the handle of a silver hard-shell carry-on suitcase, hips angled, confident and relaxed. Frame it as a vertical full-body mirror selfie at chest height with the slight phone-camera perspective and a faint screen glow. Use soft natural room lighting with gentle realistic shadows, fine grain, true fabric texture, believable sheen on the suitcase and phone, and an authentic travel-OOTD mood, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands, fingers, or phone.",
      },
    ],
  },
  {
    group: "Podcast & talking",
    scenes: [
      {
        num: "22",
        title: "Podcast guest",
        text: "Create a photorealistic vertical portrait of the woman in the reference image speaking as a guest on a high-end podcast, blending naturally as if she is genuinely mid-conversation. The setting is a warm studio with a vertical wood-slat acoustic wall behind her, soft amber studio lighting, a professional broadcast microphone on a boom arm in front of her, and a hint of a camera rig softly blurred in the background. Dress her in a tailored deep-brown corset-cut blazer dress with structured shoulders and gold statement buttons down the front, large gold disc earrings, and a few stacked gold rings; style her hair in a sleek, polished high ponytail with a clean center part. Her makeup should be glamorous yet natural and suited to her own face, glowing bronzed skin with real texture, defined brows, softly blended warm eye makeup, clean lashes, and a glossy neutral lip. Pose her seated and turned slightly off-camera as if addressing a host, one hand raised mid-gesture while she speaks, confident and engaged. Frame it as a vertical medium portrait from chest height using a 50mm lens at f/2.0 with shallow depth. Use warm directional studio light with soft realistic shadows and gentle highlights on her skin and hair, fine grain, true fabric texture, believable sheen on the gold hardware, with no flat studio glow, no over-symmetry, no glossy AI skin, and no warped hands or fingers. For a tighter shot, crop to a head-and-shoulders close-up keeping the mic and gesture in frame.",
      },
    ],
  },
];
